In [4]:
import numpy as np

In [37]:
# Matrix dot product
A = np.array([[1,1],[0,1],[0,0]])
B = np.array([[2,0],[3,4]])
np.dot(A,B)

array([[5, 4],
       [3, 4],
       [0, 0]])

In [9]:
for i in A[0]:
    print (i)

1
1


In [16]:
len(A)

3

In [41]:
for i in range(0,len(A)):
    print (A[i][0])

1
0
0


In [22]:
np.amin(B,axis=0)

array([2, 0])

In [32]:
data = np.array([ 
[4,5,8],[6,4,9],[2,7,10],[5,6,1]
])

In [27]:
xMin = np.amin(data,axis=0)
xMin[0]

2

In [28]:
yMin = np.amin(data,axis=1)
yMin[0]

4

In [35]:
xMax = np.amax(data, axis=0)
xMax[2]

10

In [46]:
u = np.zeros(4)
u

array([0., 0., 0., 0.])

In [48]:
L1 = np.array(
    [ [4,5] , [6,4], [2,7], [5,6] ] 
)

B = np.zeros((4,2))

l1Length = len(L1)

# Create u array
u = np.zeros(l1Length)

for i in range(0,l1Length):
    u[i] = L1[i][0]

# Create v array
v = np.zeros(l1Length)

for i in range(0,l1Length):
    v[i] = L1[i][1]

In [53]:
for i in range(0,l1Length):
    B[i][0] = u[i]
    
for i in range(0,l1Length):
    B[i][1] = v[i]
    
B

array([[4., 5.],
       [6., 4.],
       [2., 7.],
       [5., 6.]])

In [61]:
# Find minimums 

# for X axis : 
findXMin = np.amin(L1,axis=0)
xMin = findXMin[0]

# for Y axis : 
findYMin = np.amin(L1,axis=0)
yMin = findYMin[0]

In [65]:
# Step 2. Scan L1 and fill B. For any point Ai the box indices
# are as follows:

L1 = np.array(
    [ [4,5] , [6,4], [2,7], [5,6] ] 
)

B = np.zeros((4,2))

Dx = 2
Dy = 2
# Dz = 

l1Length = len(L1)

# Create u array
u = np.zeros(l1Length)

for i in range(0,l1Length):
    xi = L1[i][0]
    u[i] = (xi - xMin) / Dx #use truncation
    B[i][0] = u[i]
    
B

array([[1. , 0. ],
       [2. , 0. ],
       [0. , 0. ],
       [1.5, 0. ]])

In [68]:
for i in range(0,l1Length):
    yi = L1[i][1]
    u[i] = (yi - yMin) / Dy #use truncation
    B[i][1] = u[i]
    
B

array([[1. , 1.5],
       [2. , 1. ],
       [0. , 2.5],
       [1.5, 2. ]])

In [82]:
L1 = np.array(
    [ [4,5,7] , [6,4,9], [2,7,3], [5,6,8] ] 
)

# for Z axis :
findZMax = np.amax(L1, axis=1) # amax returns ndarray(?) or scalar
zMax = findZMax[1] # if there are 3 axes then xMax=findXMax[2]

# for Y axis :
findYMax = np.amax(L1, axis=1) # amax returns ndarray(?) or scalar
yMax = findYMax[1] # if there are 3 axes then xMax=findXMax[2]

findYMax

array([7, 9, 7, 8])

In [85]:
# Step 2. Scan L1 and fill B. For any point Ai the box indices
# are as follows:

B = np.zeros((4,2))

Dx = 2
Dy = 2
# Dz = 

l1Length = len(L1)

# Create u array
u = np.zeros(l1Length)

for i in range(0,l1Length):
    xi = L1[i][0]
    u[i] = (xi - xMin) / Dx # use truncation
    B[i][0] = u[i]

for i in range(0,len(u)):
    print(i)
    

0
1
2
3
